# -*- coding: utf-8 -*-
"""Credit Card Fraud Final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ql5mfUoBz294GFylXItnOBZtRQCsYCua
"""

!pip install kagglehub[pandas-datasets] imbalanced-learn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV

from imblearn.over_sampling import SMOTE

import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "creditcard.csv"

data = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "mlg-ulb/creditcardfraud",
    file_path
)

print("Original Shape:", data.shape)
data.head()

# Reduce size for faster training
data = data.sample(n=50000, random_state=42)

print("Reduced Shape:", data.shape)

X = data.drop("Class", axis=1)
y = data["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

smote = SMOTE()

X_train, y_train = smote.fit_resample(X_train, y_train)

print("After SMOTE:", np.bincount(y_train))

models = {
    "SVM": CalibratedClassifierCV(LinearSVC(), cv=3),
    "Random Forest": RandomForestClassifier(n_estimators=50, n_jobs=-1),
    "Decision Tree": DecisionTreeClassifier(max_depth=10)
}

results = {}

for name, model in models.items():

    print(f"\nTraining {name}...")

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_test)[:, 1]
    else:
        y_prob = model.decision_function(X_test)

    print(f"\n{name} Results:")
    print(classification_report(y_test, y_pred))

    results[name] = (y_pred, y_prob)

for name, (y_pred, _) in results.items():
    cm = confusion_matrix(y_test, y_pred)

    plt.figure()
    sns.heatmap(cm, annot=True, fmt='d')
    plt.title(f"Confusion Matrix - {name}")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

plt.figure()

for name, (_, y_prob) in results.items():
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    roc_auc = auc(fpr, tpr)

    plt.plot(fpr, tpr, label=f"{name} (AUC = {roc_auc:.2f})")

plt.plot([0,1],[0,1],'--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison")
plt.legend()
plt.show()

from sklearn.metrics import precision_score, recall_score, f1_score

metrics = []

for name, (y_pred, _) in results.items():
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    metrics.append([name, precision, recall, f1])

metrics_df = pd.DataFrame(metrics, columns=["Model", "Precision", "Recall", "F1 Score"])

print(metrics_df)

metrics_df.set_index("Model").plot(kind='bar')
plt.title("Model Comparison")
plt.ylabel("Score")
plt.xticks(rotation=0)
plt.show()